import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { TileImageResult } from "../types.js";

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export async function generatePreview(
  result: TileImageResult,
  sourceImagePath: string,
  model: string
): Promise<string> {
  const outputDir = result.outputDir;
  const relativeSourcePath = path.relative(
    outputDir,
    path.resolve(sourceImagePath)
  );

  const { width, height } = result.sourceImage;
  const { cols, rows, totalTiles, tileSize, estimatedTokens } = result.grid;

  const tilesJson = JSON.stringify(
    result.tiles.map((t) => ({
      index: t.index,
      row: t.row,
      col: t.col,
      x: t.x,
      y: t.y,
      width: t.width,
      height: t.height,
      filename: t.filename,
    }))
  );

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Tile Preview — ${escapeHtml(path.basename(sourceImagePath))}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #141422; color: #e0e0e0; padding: 24px 28px; }
  .header { margin-bottom: 24px; }
  .header h1 { font-size: 1.5em; margin-bottom: 10px; color: #f0f0f0; font-weight: 600; letter-spacing: -0.01em; }
  .meta { display: flex; flex-wrap: wrap; gap: 10px; font-size: 0.82em; color: #b0b0c0; }
  .meta span { background: #1e1e36; border: 1px solid #2a2a44; padding: 5px 12px; border-radius: 6px; }
  .source-container { position: relative; display: inline-block; max-width: 100%; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 24px rgba(0, 0, 0, 0.4); }
  .source-container img { display: block; max-width: 100%; height: auto; }
  .source-container svg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; }
  .source-container svg line { stroke: rgba(255, 255, 255, 0.35); stroke-width: 1.5; stroke-dasharray: 8 4; }
  .source-container svg text { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; text-anchor: middle; dominant-baseline: central; }
  .source-container svg text.tile-index { fill: #fff; }
  .source-container svg text.tile-pos { fill: rgba(255, 255, 255, 0.7); }
  .footer { margin-top: 24px; font-size: 0.75em; color: #555; text-align: center; }
</style>
</head>
<body>
<div class="header">
  <h1>${escapeHtml(path.basename(sourceImagePath))}</h1>
  <div class="meta">
    <span>${width} × ${height}</span>
    <span>Grid: ${cols} × ${rows} = ${totalTiles} tiles</span>
    <span>Tile size: ${tileSize}px</span>
    <span>Model: ${escapeHtml(model)}</span>
    <span>~${estimatedTokens.toLocaleString()} tokens</span>
  </div>
</div>

<div class="source-container">
  <img src="${escapeHtml(relativeSourcePath)}" alt="Source image" />
  <svg id="grid-overlay" viewBox="0 0 ${width} ${height}" preserveAspectRatio="xMinYMin meet"></svg>
</div>

<div class="footer">Generated by image-tiler-mcp-server</div>

<script>
(function() {
  var META = {
    width: ${width},
    height: ${height},
    cols: ${cols},
    rows: ${rows},
    tileSize: ${tileSize},
    totalTiles: ${totalTiles},
    model: ${JSON.stringify(model)}
  };
  var TILES = ${tilesJson};

  var svg = document.getElementById('grid-overlay');
  var ns = 'http://www.w3.org/2000/svg';
  // Vertical lines
  for (var c = 1; c < META.cols; c++) {
    var x = c * META.tileSize;
    var line = document.createElementNS(ns, 'line');
    line.setAttribute('x1', x); line.setAttribute('y1', 0);
    line.setAttribute('x2', x); line.setAttribute('y2', META.height);
    svg.appendChild(line);
  }
  // Horizontal lines
  for (var r = 1; r < META.rows; r++) {
    var y = r * META.tileSize;
    var line = document.createElementNS(ns, 'line');
    line.setAttribute('x1', 0); line.setAttribute('y1', y);
    line.setAttribute('x2', META.width); line.setAttribute('y2', y);
    svg.appendChild(line);
  }
  // Tile labels: index + position, with background rect
  var fontSize = Math.max(12, Math.min(META.tileSize * 0.08, 48));
  var subFontSize = fontSize * 0.65;
  for (var i = 0; i < TILES.length; i++) {
    var t = TILES[i];
    var cx = t.x + t.width / 2;
    var cy = t.y + t.height / 2;
    var padX = fontSize * 1.8;
    var padY = fontSize * 1.6;
    // Background rect
    var rect = document.createElementNS(ns, 'rect');
    rect.setAttribute('x', cx - padX / 2);
    rect.setAttribute('y', cy - padY / 2);
    rect.setAttribute('width', padX);
    rect.setAttribute('height', padY);
    rect.setAttribute('rx', fontSize * 0.25);
    rect.setAttribute('fill', 'rgba(0, 0, 0, 0.55)');
    svg.appendChild(rect);
    // Index label
    var idx = document.createElementNS(ns, 'text');
    idx.setAttribute('class', 'tile-index');
    idx.setAttribute('x', cx);
    idx.setAttribute('y', cy - subFontSize * 0.45);
    idx.setAttribute('font-size', fontSize);
    idx.textContent = String(t.index);
    svg.appendChild(idx);
    // Position label
    var pos = document.createElementNS(ns, 'text');
    pos.setAttribute('class', 'tile-pos');
    pos.setAttribute('x', cx);
    pos.setAttribute('y', cy + fontSize * 0.55);
    pos.setAttribute('font-size', subFontSize);
    pos.textContent = '(' + t.row + ',' + t.col + ')';
    svg.appendChild(pos);
  }
})();
</script>
</body>
</html>`;

  const previewPath = path.join(outputDir, "preview.html");
  await fs.writeFile(previewPath, html, "utf-8");
  return previewPath;
}
